# -*- coding: utf-8 -*-
"""Subgroup A, Question 5 Colab Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n5uZbD13YcKjPzi5_CKJTUmB1uq2auxY

**External factors and guest segmentation**
- Investigate the influence of external factors such as seasonality or local events on segment size and behavior.
- Suggest operational adjustments (e.g., staffing, promotions) for high-impact periods.
"""

# Importing From Google Drive
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/drive/MyDrive/DSA3101_data/dsa3101_clustered_data.csv")
df.head()

"""# **EDA of clusters**"""

# extract relevant columns
data = df[['q1', 'q2_1','q3', 'q6', 'q7', 'q8', 'q10', 'q12', 'cluster']]
data.info()
data.isna().sum()

data = data.dropna(subset=['cluster'])
data.info()
data.isna().sum()
data.head()

cluster_counts = df['cluster'].value_counts().sort_index()
print(cluster_counts)

def plot_bar_per_cluster(df, question, cluster_col='cluster'):
    clusters = sorted(df[cluster_col].dropna().unique())
    all_labels = df[question].dropna().unique()
    plot_data = pd.DataFrame(index=all_labels)

    for c in clusters:
        responses = df[df[cluster_col] == c][question].value_counts()
        responses = responses.reindex(all_labels, fill_value=0)
        plot_data[f'Cluster {c}'] = responses

    plot_data.plot(kind='bar', figsize=(12, 6))
    plt.title(f"Distribution of '{question}' Responses by Cluster")
    plt.xlabel("Responses")
    plt.ylabel("Count")
    plt.xticks(rotation=45)
    plt.legend(title="Cluster")
    plt.tight_layout()
    plt.show()

plot_bar_per_cluster(data, 'q1')

plot_bar_per_cluster(data, 'q2_1')



plot_bar_per_cluster(data, 'q12')